/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import crud.crud;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class FrameApp extends javax.swing.JFrame {
    crud mycode;

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
        mycode= new crud();
        mycode.tampilDataKonsultan(tabelKonsultan, "SELECT*FROM konsultan");
        mycode.tampilDataLayanan(tabelLynn, "SELECT*FROM Konsultasi_dan_Layanan_Hukum");
        mycode.tampilDataPelanggan(tabelPelanggan, "SELECT*FROM pelanggan");
        mycode.tampilDataPembayaran(tabelPembayaran, "SELECT*FROM pembayaran");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlLynn = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtIdJadwal = new javax.swing.JTextField();
        txtIdLayanan = new javax.swing.JTextField();
        txtNamaLayanan = new javax.swing.JTextField();
        btnHpsLynn = new javax.swing.JButton();
        btnSmpnLynn = new javax.swing.JButton();
        btnUbhLynn = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        txtNipKonsultanLayanan = new javax.swing.JTextField();
        txtCariLynn = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelLynn = new javax.swing.JTable();
        pnlKnsltn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTelpKonsultan = new javax.swing.JTextField();
        txtNipKonsultan = new javax.swing.JTextField();
        txtAlamatKonsultan = new javax.swing.JTextField();
        txtEmailKonsultan = new javax.swing.JTextField();
        txtCariKonsultan = new javax.swing.JTextField();
        txtNamaKonsultan = new javax.swing.JTextField();
        btnHpsKnsltn = new javax.swing.JButton();
        btnSmpnKnsltn = new javax.swing.JButton();
        btnUbhKnsltn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKonsultan = new javax.swing.JTable();
        pnlPelanggan = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNamaPelanggan = new javax.swing.JTextField();
        txtIdPelanggan = new javax.swing.JTextField();
        txtEmailPelanggan = new javax.swing.JTextField();
        txtAlamatPelanggan = new javax.swing.JTextField();
        txtCariPelanggan = new javax.swing.JTextField();
        btnHpsPlgn = new javax.swing.JButton();
        btnSmpnPlgn = new javax.swing.JButton();
        btnUbhPlgn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPelanggan = new javax.swing.JTable();
        txtTelpPelanggan = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        pnlPembayaran = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtIdLayananPem = new javax.swing.JTextField();
        txtIdPembayaran = new javax.swing.JTextField();
        txtNamaPembayaran = new javax.swing.JTextField();
        txtIdPelangganPem = new javax.swing.JTextField();
        txtCariPembayaran = new javax.swing.JTextField();
        btnHpsPem = new javax.swing.JButton();
        btnSmpnPem = new javax.swing.JButton();
        btnUbhPem = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelPembayaran = new javax.swing.JTable();
        txtReportPembayaran = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnKonsultan = new javax.swing.JButton();
        btnLayanan = new javax.swing.JButton();
        btnPelanggan = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        Content.add(pnlHome, "card6");

        pnlLynn.setBackground(new java.awt.Color(204, 204, 204));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Nama Layanan");

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("ID Jadwal");

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("ID Layanan");

        txtIdJadwal.setBackground(new java.awt.Color(255, 255, 255));
        txtIdJadwal.setForeground(new java.awt.Color(0, 0, 0));

        txtIdLayanan.setBackground(new java.awt.Color(255, 255, 255));
        txtIdLayanan.setForeground(new java.awt.Color(0, 0, 0));
        txtIdLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdLayananActionPerformed(evt);
            }
        });

        txtNamaLayanan.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaLayanan.setForeground(new java.awt.Color(0, 0, 0));

        btnHpsLynn.setText("HAPUS");
        btnHpsLynn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsLynnActionPerformed(evt);
            }
        });

        btnSmpnLynn.setText("SIMPAN");
        btnSmpnLynn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnLynnActionPerformed(evt);
            }
        });

        btnUbhLynn.setText("UBAH");
        btnUbhLynn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhLynnActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("NIP Konsultan");

        txtNipKonsultanLayanan.setBackground(new java.awt.Color(255, 255, 255));
        txtNipKonsultanLayanan.setForeground(new java.awt.Color(0, 0, 0));

        txtCariLynn.setBackground(new java.awt.Color(255, 255, 255));
        txtCariLynn.setForeground(new java.awt.Color(0, 0, 0));
        txtCariLynn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariLynnKeyReleased(evt);
            }
        });

        tabelLynn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelLynn);

        javax.swing.GroupLayout pnlLynnLayout = new javax.swing.GroupLayout(pnlLynn);
        pnlLynn.setLayout(pnlLynnLayout);
        pnlLynnLayout.setHorizontalGroup(
            pnlLynnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLynnLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(pnlLynnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .addGroup(pnlLynnLayout.createSequentialGroup()
                        .addGroup(pnlLynnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCariLynn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLynnLayout.createSequentialGroup()
                                .addGroup(pnlLynnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlLynnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlLynnLayout.createSequentialGroup()
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(49, 49, 49))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLynnLayout.createSequentialGroup()
                                            .addComponent(jLabel21)
                                            .addGap(47, 47, 47))))
                                .addGap(12, 12, 12)
                                .addGroup(pnlLynnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNamaLayanan, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(txtNipKonsultanLayanan)
                                    .addComponent(txtIdJadwal)
                                    .addComponent(txtIdLayanan))))
                        .addGroup(pnlLynnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLynnLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnSmpnLynn))
                            .addGroup(pnlLynnLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(pnlLynnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHpsLynn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUbhLynn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pnlLynnLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHpsLynn, btnSmpnLynn, btnUbhLynn});

        pnlLynnLayout.setVerticalGroup(
            pnlLynnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLynnLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(pnlLynnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(pnlLynnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSmpnLynn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLynnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(txtIdJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbhLynn))
                .addGap(13, 13, 13)
                .addGroup(pnlLynnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(txtNamaLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHpsLynn))
                .addGap(13, 13, 13)
                .addGroup(pnlLynnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(txtNipKonsultanLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(txtCariLynn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        Content.add(pnlLynn, "card4");

        pnlKnsltn.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nama");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Alamat");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Telepon");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NIP Konsultan");

        txtTelpKonsultan.setBackground(new java.awt.Color(255, 255, 255));
        txtTelpKonsultan.setForeground(new java.awt.Color(0, 0, 0));

        txtNipKonsultan.setBackground(new java.awt.Color(255, 255, 255));
        txtNipKonsultan.setForeground(new java.awt.Color(0, 0, 0));

        txtAlamatKonsultan.setBackground(new java.awt.Color(255, 255, 255));
        txtAlamatKonsultan.setForeground(new java.awt.Color(0, 0, 0));

        txtEmailKonsultan.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailKonsultan.setForeground(new java.awt.Color(0, 0, 0));

        txtCariKonsultan.setBackground(new java.awt.Color(255, 255, 255));
        txtCariKonsultan.setForeground(new java.awt.Color(0, 0, 0));
        txtCariKonsultan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKonsultanKeyReleased(evt);
            }
        });

        txtNamaKonsultan.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaKonsultan.setForeground(new java.awt.Color(0, 0, 0));

        btnHpsKnsltn.setText("HAPUS");
        btnHpsKnsltn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsKnsltnActionPerformed(evt);
            }
        });

        btnSmpnKnsltn.setText("SIMPAN");
        btnSmpnKnsltn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnKnsltnActionPerformed(evt);
            }
        });

        btnUbhKnsltn.setText("UBAH");
        btnUbhKnsltn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhKnsltnActionPerformed(evt);
            }
        });

        tabelKonsultan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelKonsultan);

        javax.swing.GroupLayout pnlKnsltnLayout = new javax.swing.GroupLayout(pnlKnsltn);
        pnlKnsltn.setLayout(pnlKnsltnLayout);
        pnlKnsltnLayout.setHorizontalGroup(
            pnlKnsltnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKnsltnLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(pnlKnsltnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlKnsltnLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(91, 91, 91)
                        .addComponent(txtEmailKonsultan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnHpsKnsltn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKnsltnLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(78, 78, 78)
                        .addComponent(txtAlamatKonsultan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKnsltnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCariKonsultan, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlKnsltnLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(87, 87, 87)
                            .addComponent(txtNamaKonsultan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlKnsltnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlKnsltnLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtNipKonsultan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btnSmpnKnsltn, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGroup(pnlKnsltnLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(72, 72, 72)
                            .addComponent(txtTelpKonsultan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btnUbhKnsltn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pnlKnsltnLayout.setVerticalGroup(
            pnlKnsltnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKnsltnLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(pnlKnsltnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKnsltnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNipKonsultan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(btnSmpnKnsltn))
                .addGap(13, 13, 13)
                .addGroup(pnlKnsltnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtTelpKonsultan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbhKnsltn))
                .addGap(13, 13, 13)
                .addGroup(pnlKnsltnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtEmailKonsultan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHpsKnsltn))
                .addGap(13, 13, 13)
                .addGroup(pnlKnsltnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtAlamatKonsultan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlKnsltnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtNamaKonsultan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(txtCariKonsultan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Content.add(pnlKnsltn, "card3");

        pnlPelanggan.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Email");

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Alamat");

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Nama ");

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("ID Pelanggan");

        txtNamaPelanggan.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaPelanggan.setForeground(new java.awt.Color(0, 0, 0));

        txtIdPelanggan.setBackground(new java.awt.Color(255, 255, 255));
        txtIdPelanggan.setForeground(new java.awt.Color(0, 0, 0));

        txtEmailPelanggan.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailPelanggan.setForeground(new java.awt.Color(0, 0, 0));

        txtAlamatPelanggan.setBackground(new java.awt.Color(255, 255, 255));
        txtAlamatPelanggan.setForeground(new java.awt.Color(0, 0, 0));

        txtCariPelanggan.setBackground(new java.awt.Color(255, 255, 255));
        txtCariPelanggan.setForeground(new java.awt.Color(0, 0, 0));
        txtCariPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPelangganKeyReleased(evt);
            }
        });

        btnHpsPlgn.setText("HAPUS");
        btnHpsPlgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsPlgnActionPerformed(evt);
            }
        });

        btnSmpnPlgn.setText("SIMPAN");
        btnSmpnPlgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnPlgnActionPerformed(evt);
            }
        });

        btnUbhPlgn.setText("UBAH");
        btnUbhPlgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhPlgnActionPerformed(evt);
            }
        });

        tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelPelanggan);

        txtTelpPelanggan.setBackground(new java.awt.Color(255, 255, 255));
        txtTelpPelanggan.setForeground(new java.awt.Color(0, 0, 0));

        jLabel22.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Telepon");

        javax.swing.GroupLayout pnlPelangganLayout = new javax.swing.GroupLayout(pnlPelanggan);
        pnlPelanggan.setLayout(pnlPelangganLayout);
        pnlPelangganLayout.setHorizontalGroup(
            pnlPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPelangganLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(pnlPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPelangganLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSmpnPlgn))
                    .addGroup(pnlPelangganLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnUbhPlgn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPelangganLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(txtAlamatPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnHpsPlgn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPelangganLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(txtTelpPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPelangganLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(95, 95, 95)
                        .addComponent(txtEmailPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCariPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        pnlPelangganLayout.setVerticalGroup(
            pnlPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPelangganLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(pnlPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSmpnPlgn))
                .addGap(13, 13, 13)
                .addGroup(pnlPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbhPlgn))
                .addGap(13, 13, 13)
                .addGroup(pnlPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtAlamatPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHpsPlgn))
                .addGap(13, 13, 13)
                .addGroup(pnlPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtEmailPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPelangganLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(txtTelpPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPelangganLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCariPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Content.add(pnlPelanggan, "card5");

        pnlPembayaran.setBackground(new java.awt.Color(204, 204, 204));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nama Pembayaran");

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("ID Pelanggan");

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("ID Layanan");

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("ID Pembayaran");

        txtIdLayananPem.setBackground(new java.awt.Color(255, 255, 255));
        txtIdLayananPem.setForeground(new java.awt.Color(0, 0, 0));

        txtIdPembayaran.setBackground(new java.awt.Color(255, 255, 255));
        txtIdPembayaran.setForeground(new java.awt.Color(0, 0, 0));

        txtNamaPembayaran.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaPembayaran.setForeground(new java.awt.Color(0, 0, 0));

        txtIdPelangganPem.setBackground(new java.awt.Color(255, 255, 255));
        txtIdPelangganPem.setForeground(new java.awt.Color(0, 0, 0));

        txtCariPembayaran.setBackground(new java.awt.Color(255, 255, 255));
        txtCariPembayaran.setForeground(new java.awt.Color(0, 0, 0));
        txtCariPembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPembayaranKeyReleased(evt);
            }
        });

        btnHpsPem.setText("HAPUS");
        btnHpsPem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsPemActionPerformed(evt);
            }
        });

        btnSmpnPem.setText("SIMPAN");
        btnSmpnPem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnPemActionPerformed(evt);
            }
        });

        btnUbhPem.setText("UBAH");
        btnUbhPem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhPemActionPerformed(evt);
            }
        });

        tabelPembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelPembayaran);

        txtReportPembayaran.setBackground(new java.awt.Color(255, 255, 255));
        txtReportPembayaran.setForeground(new java.awt.Color(0, 0, 0));

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Report");

        javax.swing.GroupLayout pnlPembayaranLayout = new javax.swing.GroupLayout(pnlPembayaran);
        pnlPembayaran.setLayout(pnlPembayaranLayout);
        pnlPembayaranLayout.setHorizontalGroup(
            pnlPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPembayaranLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(pnlPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPembayaranLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(46, 46, 46)
                        .addComponent(txtIdPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnSmpnPem))
                    .addGroup(pnlPembayaranLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(79, 79, 79)
                        .addComponent(txtIdLayananPem, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnUbhPem, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPembayaranLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(63, 63, 63)
                        .addComponent(txtIdPelangganPem, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnHpsPem, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPembayaranLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(15, 15, 15)
                        .addComponent(txtNamaPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPembayaranLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(117, 117, 117)
                        .addComponent(txtReportPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCariPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnlPembayaranLayout.setVerticalGroup(
            pnlPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPembayaranLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(pnlPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(txtIdPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSmpnPem))
                .addGap(13, 13, 13)
                .addGroup(pnlPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtIdLayananPem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbhPem))
                .addGap(13, 13, 13)
                .addGroup(pnlPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txtIdPelangganPem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHpsPem))
                .addGap(13, 13, 13)
                .addGroup(pnlPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtNamaPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(txtReportPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(txtCariPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        Content.add(pnlPembayaran, "card5");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("SISTEM INFORMASI HUKUM");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setForeground(new java.awt.Color(255, 255, 255));

        btnKonsultan.setBackground(new java.awt.Color(204, 204, 204));
        btnKonsultan.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnKonsultan.setForeground(new java.awt.Color(0, 0, 0));
        btnKonsultan.setText("KONSULTAN");
        btnKonsultan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonsultanActionPerformed(evt);
            }
        });

        btnLayanan.setBackground(new java.awt.Color(204, 204, 204));
        btnLayanan.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnLayanan.setForeground(new java.awt.Color(0, 0, 0));
        btnLayanan.setText("LAYANAN");
        btnLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayananActionPerformed(evt);
            }
        });

        btnPelanggan.setBackground(new java.awt.Color(204, 204, 204));
        btnPelanggan.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnPelanggan.setForeground(new java.awt.Color(0, 0, 0));
        btnPelanggan.setText("PELANGGAN");
        btnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelangganActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(204, 204, 204));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnPembayaran.setBackground(new java.awt.Color(204, 204, 204));
        btnPembayaran.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnPembayaran.setForeground(new java.awt.Color(0, 0, 0));
        btnPembayaran.setText("PEMBAYARAN");
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLayanan)
                    .addComponent(btnKonsultan, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPelanggan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPembayaran, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnKonsultan, btnLayanan, btnPelanggan, btnPembayaran});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKonsultan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLayanan)
                .addGap(18, 18, 18)
                .addComponent(btnPelanggan)
                .addGap(18, 18, 18)
                .addComponent(btnPembayaran)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnKonsultan, btnLayanan, btnPelanggan, btnPembayaran});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnKonsultanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonsultanActionPerformed
        Content.removeAll(); 
        Content.add(pnlKnsltn);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnKonsultanActionPerformed

    private void btnLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayananActionPerformed
        Content.removeAll(); 
        Content.add(pnlLynn);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnLayananActionPerformed

    private void btnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelangganActionPerformed
        Content.removeAll(); 
        Content.add(pnlPelanggan);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnPelangganActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        Content.removeAll(); 
        Content.add(pnlPembayaran);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void btnSmpnKnsltnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnKnsltnActionPerformed
        try {
            if(txtNipKonsultan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "NIP Konsultan Belum Diisi");
                txtNipKonsultan.requestFocus();
            } else if(txtTelpKonsultan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No Telepon Belum Diisi");
                txtTelpKonsultan.requestFocus();
            } else if(txtEmailKonsultan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Email Belum Diisi");
                txtEmailKonsultan.requestFocus();
            } else if(txtAlamatKonsultan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Alamat Belum Diisi");
                txtAlamatKonsultan.requestFocus();
            } else if(txtNamaKonsultan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Belum Diisi");
                txtNamaKonsultan.requestFocus();
            } else {
                mycode.simpanKonsultan02(txtNipKonsultan.getText(), txtTelpKonsultan.getText(),
                                         txtEmailKonsultan.getText(), txtAlamatKonsultan.getText(),
                                         txtNamaKonsultan.getText());

                // Refresh tabel
                mycode.tampilDataKonsultan(tabelKonsultan, "SELECT*FROM Konsultan");

                // Cek duplikasi
                if (mycode.duplikasi == true){
                    txtTelpKonsultan.setText(mycode.CEK_TELP_KONSULTAN);
                    txtEmailKonsultan.setText(mycode.CEK_EMAIL_KONSULTAN);
                    txtAlamatKonsultan.setText(mycode.CEK_ALAMAT_KONSULTAN);
                    txtNamaKonsultan.setText(mycode.CEK_NAMA_KONSULTAN);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnKnsltnActionPerformed

    private void btnUbhKnsltnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhKnsltnActionPerformed
        try {
            mycode.ubahKonsultan(txtNipKonsultan.getText(), txtTelpKonsultan.getText(),
                                 txtEmailKonsultan.getText(), txtAlamatKonsultan.getText(),
                                 txtNamaKonsultan.getText());

            // Refresh tabel
            mycode.tampilDataKonsultan(tabelKonsultan, "SELECT*FROM konsultan");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhKnsltnActionPerformed

    private void btnHpsKnsltnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsKnsltnActionPerformed
        try {
            mycode.hapusKonsultan(txtNipKonsultan.getText());
            mycode.tampilDataKonsultan(tabelKonsultan, "SELECT*FROM Konsultan");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsKnsltnActionPerformed

    private void txtCariKonsultanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKonsultanKeyReleased
        String c = txtCariKonsultan.getText();
        String cari = "SELECT*FROM Konsultan WHERE NIP_Konsultan LIKE '%"+c+"%'"+
                      "OR Telp LIKE '%"+c+"%' OR Email LIKE '%"+c+"%'"+
                      "OR Alamat LIKE '%"+c+"%' OR Nama LIKE '%"+c+"%'";
        mycode.tampilDataKonsultan(tabelKonsultan, cari);
    }//GEN-LAST:event_txtCariKonsultanKeyReleased

    private void btnUbhPlgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhPlgnActionPerformed
        try {
            mycode.ubahPelanggan(txtIdPelanggan.getText(), txtNamaPelanggan.getText(), 
                                 txtAlamatPelanggan.getText(), txtEmailPelanggan.getText(), 
                                 txtTelpPelanggan.getText());

            // Refresh tabel
            mycode.tampilDataPelanggan(tabelPelanggan, "SELECT*FROM Pelanggan");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhPlgnActionPerformed

    private void btnSmpnPlgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnPlgnActionPerformed
        try {
            if(txtIdPelanggan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Pelanggan Belum Diisi");
                txtIdPelanggan.requestFocus();
            } else if(txtNamaPelanggan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Belum Diisi");
                txtNamaPelanggan.requestFocus();
            } else if(txtAlamatPelanggan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Alamat Belum Diisi");
                txtAlamatPelanggan.requestFocus();
            } else if(txtEmailPelanggan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Email Belum Diisi");
                txtEmailPelanggan.requestFocus();
            } else if(txtTelpPelanggan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No Telepon Belum Diisi");
                txtTelpPelanggan.requestFocus();
            } else {
                mycode.simpanPelanggan02(txtIdPelanggan.getText(), txtNamaPelanggan.getText(), 
                                        txtAlamatPelanggan.getText(), txtEmailPelanggan.getText(), 
                                        txtTelpPelanggan.getText());

                // Refresh tabel
                mycode.tampilDataPelanggan(tabelPelanggan, "SELECT*FROM Pelanggan");

                // Cek duplikasi
                if (mycode.duplikasi == true){
                    txtNamaPelanggan.setText(mycode.CEK_NAMA_PELANGGAN);
                    txtAlamatPelanggan.setText(mycode.CEK_ALAMAT_PELANGGAN);
                    txtEmailPelanggan.setText(mycode.CEK_EMAIL_PELANGGAN);
                    txtTelpPelanggan.setText(mycode.CEK_TELP_PELANGGAN);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnPlgnActionPerformed

    private void btnHpsPlgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsPlgnActionPerformed
        try {
            mycode.hapusPelanggan(txtIdPelanggan.getText());
            mycode.tampilDataPelanggan(tabelPelanggan, "SELECT*FROM Pelanggan");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsPlgnActionPerformed

    private void txtCariPelangganKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPelangganKeyReleased
        String c = txtCariPelanggan.getText();
        String cari = "SELECT*FROM Pelanggan WHERE ID_Pelanggan LIKE '%"+c+"%'"+
                      "OR Nama LIKE '%"+c+"%' OR Alamat LIKE '%"+c+"%'"+
                      "OR Email LIKE '%"+c+"%' OR Telp LIKE '%"+c+"%'";
        mycode.tampilDataPelanggan(tabelPelanggan, cari);
    }//GEN-LAST:event_txtCariPelangganKeyReleased

    private void txtCariPembayaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPembayaranKeyReleased
        String c = txtCariPembayaran.getText();
        String cari = "SELECT*FROM Pembayaran WHERE ID_Pembayaran LIKE '%"+c+"%'"+
                      "OR ID_Layanan LIKE '%"+c+"%' OR ID_Pelanggan LIKE '%"+c+"%'"+
                      "OR Nama LIKE '%"+c+"%' OR Report_Pembayaran LIKE '%"+c+"%'";
        mycode.tampilDataPembayaran(tabelPembayaran, cari);
    }//GEN-LAST:event_txtCariPembayaranKeyReleased

    private void btnHpsPemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsPemActionPerformed
        try {
            mycode.hapusPembayaran(txtIdPembayaran.getText());
            mycode.tampilDataPembayaran(tabelPembayaran, "SELECT*FROM Pembayaran");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsPemActionPerformed

    private void btnSmpnPemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnPemActionPerformed
        try {
            if(txtIdPembayaran.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Pembayaran Belum Diisi");
                txtIdPembayaran.requestFocus();
            } else if(txtIdLayananPem.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "ID Layanan Belum Diisi");
                txtIdLayananPem.requestFocus();
            } else if(txtIdPelangganPem.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "ID Pelanggan Belum Diisi");
                txtIdPelangganPem.requestFocus();
            } else if(txtNamaPembayaran.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Pembayaran Belum Diisi");
                txtNamaPembayaran.requestFocus();
            } else if(txtReportPembayaran.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Report Pembayaran Belum Diisi");
                txtReportPembayaran.requestFocus();
            } else {
                mycode.simpanPembayaran02(txtIdPembayaran.getText(), txtIdLayananPem.getText(),
                                          txtIdPelangganPem.getText(), txtNamaPembayaran.getText(),
                                          txtReportPembayaran.getText());

                // Refresh tabel
                mycode.tampilDataPembayaran(tabelPembayaran, "SELECT*FROM Pembayaran");

                // Cek duplikasi
                if (mycode.duplikasi == true){
                    txtIdLayananPem.setText(mycode.CEK_ID_LAYANAN_PEM);
                    txtIdPelangganPem.setText(mycode.CEK_ID_PELANGGAN_PEM);
                    txtNamaPembayaran.setText(mycode.CEK_NAMA_PEMBAYARAN);
                    txtReportPembayaran.setText(mycode.CEK_REPORT_PEMBAYARAN);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnPemActionPerformed

    private void btnUbhPemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhPemActionPerformed
        try {
            mycode.ubahPembayaran(txtIdPembayaran.getText(), txtIdLayananPem.getText(),
                                  txtIdPelangganPem.getText(), txtNamaPembayaran.getText(),
                                  txtReportPembayaran.getText());

            // Refresh tabel
            mycode.tampilDataPembayaran(tabelPembayaran, "SELECT*FROM Pembayaran");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhPemActionPerformed

    private void txtCariLynnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariLynnKeyReleased
        String c = txtCariLynn.getText();
        String cari = "SELECT*FROM Konsultasi_dan_Layanan_Hukum WHERE ID_Layanan LIKE '%"+c+"%'"+
                      "OR ID_Jadwal LIKE '%"+c+"%' OR Nama LIKE '%"+c+"%'"+
                      "OR NIP_konsultan LIKE '%"+c+"%'";
        mycode.tampilDataLayanan(tabelLynn, cari);
    }//GEN-LAST:event_txtCariLynnKeyReleased

    private void btnUbhLynnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhLynnActionPerformed
        try {
            mycode.ubahLayanan(txtIdLayanan.getText(), txtIdJadwal.getText(),
                               txtNamaLayanan.getText(), txtNipKonsultanLayanan.getText());

            // Refresh tabel
            mycode.tampilDataLayanan(tabelLynn, "SELECT*FROM Konsultasi_dan_Layanan_Hukum");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhLynnActionPerformed

    private void btnSmpnLynnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnLynnActionPerformed
        try {
            if(txtIdLayanan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Layanan Belum Diisi");
                txtIdLayanan.requestFocus();
            } else if(txtIdJadwal.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Jadwal Belum Diisi");
                txtIdJadwal.requestFocus();
            } else if(txtNamaLayanan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Layanan Belum Diisi");
                txtNamaLayanan.requestFocus();
            } else if(txtNipKonsultanLayanan.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "NIP Konsultan Belum Diisi");
                txtNipKonsultanLayanan.requestFocus();
            } else {
                mycode.simpanLayanan02(txtIdLayanan.getText(), txtIdJadwal.getText(),
                                      txtNamaLayanan.getText(), txtNipKonsultanLayanan.getText());
                mycode.tampilDataLayanan(tabelLynn, "SELECT*FROM Konsultasi_dan_Layanan_Hukum");
                if (mycode.duplikasi == true){
                    txtIdJadwal.setText(mycode.CEK_ID_JADWAL);
                    txtNamaLayanan.setText(mycode.CEK_NAMA_LAYANAN);
                    txtNipKonsultanLayanan.setText(mycode.CEK_NIP_KONSULTAN_LYN);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnLynnActionPerformed

    private void btnHpsLynnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsLynnActionPerformed
        try {
            mycode.hapusLayanan(txtIdLayanan.getText());
            mycode.tampilDataLayanan(tabelLynn, "SELECT*FROM Konsultasi_dan_Layanan_Hukum");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsLynnActionPerformed

    private void txtIdLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdLayananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdLayananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHpsKnsltn;
    private javax.swing.JButton btnHpsLynn;
    private javax.swing.JButton btnHpsPem;
    private javax.swing.JButton btnHpsPlgn;
    private javax.swing.JButton btnKonsultan;
    private javax.swing.JButton btnLayanan;
    private javax.swing.JButton btnPelanggan;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnSmpnKnsltn;
    private javax.swing.JButton btnSmpnLynn;
    private javax.swing.JButton btnSmpnPem;
    private javax.swing.JButton btnSmpnPlgn;
    private javax.swing.JButton btnUbhKnsltn;
    private javax.swing.JButton btnUbhLynn;
    private javax.swing.JButton btnUbhPem;
    private javax.swing.JButton btnUbhPlgn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlKnsltn;
    private javax.swing.JPanel pnlLynn;
    private javax.swing.JPanel pnlPelanggan;
    private javax.swing.JPanel pnlPembayaran;
    private javax.swing.JTable tabelKonsultan;
    private javax.swing.JTable tabelLynn;
    private javax.swing.JTable tabelPelanggan;
    private javax.swing.JTable tabelPembayaran;
    private javax.swing.JTextField txtAlamatKonsultan;
    private javax.swing.JTextField txtAlamatPelanggan;
    private javax.swing.JTextField txtCariKonsultan;
    private javax.swing.JTextField txtCariLynn;
    private javax.swing.JTextField txtCariPelanggan;
    private javax.swing.JTextField txtCariPembayaran;
    private javax.swing.JTextField txtEmailKonsultan;
    private javax.swing.JTextField txtEmailPelanggan;
    private javax.swing.JTextField txtIdJadwal;
    private javax.swing.JTextField txtIdLayanan;
    private javax.swing.JTextField txtIdLayananPem;
    private javax.swing.JTextField txtIdPelanggan;
    private javax.swing.JTextField txtIdPelangganPem;
    private javax.swing.JTextField txtIdPembayaran;
    private javax.swing.JTextField txtNamaKonsultan;
    private javax.swing.JTextField txtNamaLayanan;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtNamaPembayaran;
    private javax.swing.JTextField txtNipKonsultan;
    private javax.swing.JTextField txtNipKonsultanLayanan;
    private javax.swing.JTextField txtReportPembayaran;
    private javax.swing.JTextField txtTelpKonsultan;
    private javax.swing.JTextField txtTelpPelanggan;
    // End of variables declaration//GEN-END:variables
}
